export const theme = {
  storeName: 'Livro Aberto',
  tagline: 'Livros para todos os cantos 📖',
  colors: {
    primary: '#0c74e4',
    primaryDark: '#095dbb',
    primaryLight: '#e6f2fd',
    secondary: '#1CF6FF',
    secondaryLight: '#e6f2fd',
    secondaryDark: '#0c74e4',
    accent: '#FF9B1B',
    mintLight: '#e6f9f5',
    mintDark: '#0d9488',
    dark: '#111827',
    light: '#f4f7fb',
    white: '#ffffff',
    greyLight: '#e2e8f0',
    greyDark: '#64748b',
    error: '#b91c1c',
    errorLight: '#fee2e2',
    danger: '#b91c1c',
    dangerLight: '#fee2e2',
    success: '#15803d',
    successLight: '#dcfce7',
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 999,
  },
};